// Generates src/embedded_ephe.c: the ephemeris files as byte arrays, plus a
// lookup that hands them to Swiss Ephemeris as read-only FILE* via fmemopen.
// Run through `npm run generate` before building the addon.

const { readFileSync, readdirSync, writeFileSync, mkdirSync } = require("fs");
const { join } = require("path");

const EPHE_DIR = join(__dirname, "..", "ephe");
const OUT = join(__dirname, "..", "src", "embedded_ephe.c");

const files = readdirSync(EPHE_DIR).filter(f => /\.(se1|txt)$/.test(f)).sort();
if (!files.length) throw new Error(`no ephemeris files in ${EPHE_DIR}`);

const chunks = [];
chunks.push(`/* Generated by tools/gen_embedded.js - do not edit. */

#include <stdio.h>
#include <string.h>
#include "embedded_ephe.h"
`);

const entries = [];
let total = 0;

for (const [i, name] of files.entries()) {
	const data = readFileSync(join(EPHE_DIR, name));
	total += data.length;
	const symbol = `ephe_data_${i}`;
	const body = [];
	for (let offset = 0; offset < data.length; offset += 16) {
		const line = [];
		for (const byte of data.subarray(offset, offset + 16)) line.push(`0x${byte.toString(16).padStart(2, "0")}`);
		body.push("\t" + line.join(","));
	}
	chunks.push(`\n/* ${name}: ${data.length} bytes */\nstatic const unsigned char ${symbol}[] = {\n${body.join(",\n")}\n};\n`);
	entries.push(`\t{ "${name}", ${symbol}, sizeof(${symbol}) }`);
}

chunks.push(`
typedef struct { const char *name; const unsigned char *data; size_t len; } embedded_file;

static const embedded_file embedded_files[] = {
${entries.join(",\n")}
};

#define EMBEDDED_COUNT (sizeof(embedded_files) / sizeof(embedded_files[0]))

FILE *swi_fopen_embedded(const char *fname)
{
	size_t i;
	if (fname == NULL)
		return NULL;
	for (i = 0; i < EMBEDDED_COUNT; i++) {
		if (strcmp(fname, embedded_files[i].name) == 0)
			return fmemopen((void *) embedded_files[i].data, embedded_files[i].len, "rb");
	}
	return NULL;
}

int swi_embedded_count(void)
{
	return (int) EMBEDDED_COUNT;
}
`);

mkdirSync(join(__dirname, "..", "src"), { recursive: true });
writeFileSync(OUT, chunks.join(""), "utf8");
console.log(`embedded ${files.length} files, ${total} bytes -> ${OUT}`);
